---
Name: iqseo
---
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - IQnection\SEO\SiteConfig\SiteConfigExtension
Page:
  extensions:
    - IQnection\SEO\Page\PageExtension
PageController:
  extensions:
    - IQnection\SEO\Page\PageControllerExtension
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - iqnection-modules/seo:css/leftandmainadditions.css
  extra_requirements_javascript:
    - iqnection-modules/seo:javascript/leftandmainadditions.js
---