---
Name: iqseo
---
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - IqSeoSiteConfigExtension
Page:
  extensions:
    - IqSeoPageExtension
PageController:
  extensions:
    - IqSeoPageControllerExtension
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - iq-seo/cms/css/leftandmainadditions.css
  extra_requirements_javascript:
    - iq-seo/cms/javascript/leftandmainadditions.js
---