SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - IqSeoSiteConfig
Page:
  extensions:
    - IqSeoPage
PageController:
  extensions:
    - IqSeoPageController
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - iq-seo/css/leftandmainadditions.css
  extra_requirements_javascript:
    - iq-seo/javascript/leftandmainadditions.js
